<template>
  <div>
    <div class="navbar">
      <router-link to="/">Home</router-link>
      <router-link to="/profile">Profile</router-link>
      <router-link to="/event" class="active">Events</router-link>
    </div>

    <header>
      <h1>Skate the Wave Meetups</h1>
      <p>Find upcoming skate meetups at various spots around Wilmington!</p>
    </header>

    <main>
      <!-- Events -->
      <section id="schedule">
        <h2>Upcoming Events</h2>
        <table v-if="databaseEvents.length">
          <tr>
            <th>Event ID</th>
            <th>Date</th>
            <th>Time</th>
            <th>Description</th>
          </tr>
          <!-- Populate -->
          <tr v-for="(event, index) in databaseEvents" :key="'db_' + index" :class="{ 'even': index % 2 === 0, 'hover': hoverIndex === index }" @mouseover="hoverIndex = index" @mouseleave="hoverIndex = null">
            <td>{{ event.eventID }}</td>
            <td>{{ event.date }}</td>
            <td>{{ event.time }}</td>
            <td>{{ event.description }}</td>
          </tr>
        </table>
        <p v-if="databaseEvents.length === 0">No upcoming events found.</p>
        <p v-if="error" class="error-message">{{ error }}</p>

        <!-- Add Event Form -->
        <form @submit.prevent="addEvent">
          <h2>Add New Event</h2>
          <div>
            <label for="eventDate">Date:</label>
            <input type="date" id="eventDate" v-model="newEvent.date" required>
          </div>
          <div>
            <label for="eventTime">Time:</label>
            <input type="time" id="eventTime" v-model="newEvent.time" required>
          </div>
          <div>
            <label for="eventDescription">Description:</label>
            <textarea id="eventDescription" v-model="newEvent.description" required></textarea>
          </div>
          <button type="submit">Add Event</button>
        </form>
      </section>
    </main>
  </div>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      databaseEvents: [],
      hoverIndex: null,
      error: null,
      newEvent: {
        date: '',
        time: '',
        details: ''
      }
    };
  },
  mounted() {
    // Fetch SQLite database
    this.fetchEvents();
  },
  methods: {
    async fetchEvents() {
      try {
        const response = await fetch('/api/events/all');
        if (!response.ok) {
          throw new Error('Failed to fetch events');
        }
        this.databaseEvents = await response.json();
      } catch (error) {
        console.error(error);
        this.error = 'Failed to fetch events from the database';
      }
    },
    async addEvent() {
      try {
        const response = await axios.post('http://localhost:8000/events/create', {
          eventID: '', // This will be generated by the server
          date: this.newEvent.date,
          time: this.newEvent.time,
          description: this.newEvent.description
        });

        if (!response.ok) {
          throw new Error('Failed to add new event');
        }
        // Clear the form fields after successful addition
        this.newEvent.date = '';
        this.newEvent.time = '';
        this.newEvent.description = '';
        // Fetch updated events
        this.fetchEvents();
      } catch (error) {
        console.error(error);
        this.error = 'Failed to add new event';
      }
    }
  }
};
</script>


<style scoped>

.error-message {
  color: red;
  font-weight: bold;
}

body {
  font-family: "Poppins", sans-serif;
  margin: 0;
  padding: 0;
  background-color: teal;
  color: #fff;
}

header {
  background-color: gold;
  padding: 20px;
  text-align: center;
}

h1 {
  margin: 0;
  padding: 0;
  font-size: 36px;
}

p {
  margin: 10px 0;
  font-size: 18px;
}

main {
  padding: 20px;
}

section#schedule {
  background-color: #1a1a1a;
  padding: 20px;
  border-radius: 10px;
  margin-top: 20px;
}

h2 {
  color: gold;
}

table {
  width: 100%;
  border-collapse: collapse;
}

th, td {
  border-bottom: 1px solid #fff;
  padding: 10px;
  text-align: left;
}

th {
  background-color: teal;
  color: gold;
}

tr.even {
  background-color: #333;
}

tr.hover {
  background-color: #555;
}

.navbar {
  overflow: hidden;
  background-color: #333;
}

.navbar a {
  float: left;
  display: block;
  color: white;
  text-align: center;
  padding: 14px 20px;
  text-decoration: none;
}

.navbar a:hover {
  background-color: #ddd;
  color: black;
}

.active {
  background-color: #ddd;
  color: black;
}
</style>
